// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var addNode, makeLeafElement, makeReplyFunction, nodes, socket;
    makeReplyFunction = function(id) {
      return function() {
        var content;
        content = window.prompt('Reply', 'Write your reply');
        if (content !== null) {
          return $.ajax({
            type: 'PUT',
            url: "/" + id,
            data: content
          });
        }
      };
    };
    nodes = {};
    addNode = function(id, parentId, content) {
      var element, parent;
      parent = nodes[parentId];
      element = makeLeafElement(id, content);
      nodes[id] = {
        element: element
      };
      return parent.element.append(element);
    };
    makeLeafElement = function(id, content) {
      return $('<div/>').addClass('node').append($('<div/>').addClass('controls').append($('<a href="#"/>').text('⤸').click(makeReplyFunction(id)))).append($('<div/>').addClass('content').text(content)).append($('<div/>').addClass('branches'));
    };
    nodes['0'] = {
      element: makeLeafElement(0, '')
    };
    $("body").append(nodes[0].element);
    socket = new WebSocket("ws://" + location.hostname + ":9160");
    return socket.onopen = function(event) {
      return socket.onmessage = function(event) {
        var content, id, parentId, _ref;
        _ref = JSON.parse(event.data), id = _ref[0], parentId = _ref[1], content = _ref[2];
        return addNode(id, parentId, content);
      };
    };
  });

}).call(this);
